"""tabelas do schema market (site.md §4.3 + ADR-018)

Revision ID: 469ddc79c8ee
Revises: 000001
Create Date: 2026-09-22

Cria as 20 tabelas do schema `market`, as partições anuais de `daily_quotes`
(sem elas o INSERT falha: o Postgres não cria partição sozinho) e semeia
`data_sources` com o resultado da verificação de termos de `docs/fontes-de-dados.md`.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from alpherion.db.partitions import FIRST_YEAR, create_year_partitions

#: Fontes do pipeline e o estado da verificação (docs/fontes-de-dados.md, 21/09/2026).
#: `terms_checked_at = None` significa **bloqueada em produção** (ADR-017).
DATA_SOURCES: tuple[dict[str, object], ...] = (
    {
        "source": "cvm",
        "url": "https://dados.cvm.gov.br/",
        "attribution": "Fonte: CVM",
        "license_note": (
            "Dados abertos do Poder Executivo Federal (Lei 12.527/2011; Decreto 8.777/2016). "
            "Uso e redistribuição livres com atribuição."
        ),
        "terms_checked_at": date(2026, 9, 21),
    },
    {
        "source": "tesouro",
        "url": "https://www.tesourotransparente.gov.br/",
        "attribution": "Fonte: Tesouro Nacional",
        "license_note": "ODbL (Open Data Commons), declarada no dataset do Tesouro Direto.",
        "terms_checked_at": date(2026, 9, 21),
    },
    {
        "source": "bcb",
        "url": "https://api.bcb.gov.br/dados/serie/",
        "attribution": "Fonte: Banco Central do Brasil",
        "license_note": "Dados abertos do BCB (catálogo dadosabertos.bcb.gov.br).",
        "terms_checked_at": date(2026, 9, 21),
    },
    {
        "source": "b3",
        "url": "https://www.b3.com.br/",
        "attribution": "Fonte: B3",
        "license_note": (
            "BLOQUEADA: termos do site vedam uso comercial sem autorização escrita e a "
            "Política de Consumo de Market Data 2026 exige licença (Atraso Snapshot + "
            "Produtizador). Ver ADR-017."
        ),
        "terms_checked_at": None,
    },
    {
        "source": "coingecko",
        "url": "https://www.coingecko.com/en/api",
        "attribution": "Dados por CoinGecko",
        "license_note": (
            "BLOQUEADA: o plano Demo não permite uso comercial. Produção exige plano pago "
            "ou outra fonte licenciada. Ver ADR-017."
        ),
        "terms_checked_at": None,
    },
    {
        "source": "agenda_macro",
        "url": "content/agenda-macro.json",
        "attribution": "Fontes: BCB, IBGE, FGV, Fed, B3",
        "license_note": "Datas públicas dos calendários oficiais, transcritas com source_url.",
        "terms_checked_at": date(2026, 9, 21),
    },
)

revision: str = "469ddc79c8ee"
down_revision: str | None = "000001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `unaccent()` é STABLE (depende do dicionário de busca) e o Postgres recusa função
    # não-IMMUTABLE em índice. Este wrapper fixa o dicionário e é seguro para indexar:
    # é o padrão recomendado na documentação do pg_trgm/unaccent.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION market.immutable_unaccent(text)
        RETURNS text
        LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS
        $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_documents",
        sa.Column("protocol", sa.String(length=40), nullable=False),
        sa.Column("cvm_code", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=120), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.Date(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("protocol", name=op.f("pk_company_documents")),
        schema="market",
    )
    op.create_index(
        "ix_company_documents_cvm_code_delivered",
        "company_documents",
        ["cvm_code", "delivered_at"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "ix_company_documents_delivered_at",
        "company_documents",
        ["delivered_at"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "ix_company_documents_ticker_delivered",
        "company_documents",
        ["ticker", "delivered_at"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "company_facts",
        sa.Column("cvm_code", sa.Integer(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("shares_outstanding", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("free_float", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("capital_social", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cvm_code", "reference_date", name=op.f("pk_company_facts")),
        schema="market",
    )
    op.create_table(
        "crypto_assets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_stablecoin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("market_cap_rank", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crypto_assets")),
        schema="market",
    )
    op.create_table(
        "daily_quotes",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("close_adjusted", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("trades", sa.BigInteger(), nullable=True),
        sa.Column(
            "adj_factor", sa.Numeric(precision=18, scale=8), server_default="1", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ticker", "date", name=op.f("pk_daily_quotes")),
        schema="market",
        postgresql_partition_by="RANGE (date)",
    )
    op.create_index("ix_daily_quotes_date", "daily_quotes", ["date"], unique=False, schema="market")
    op.create_table(
        "data_sources",
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("license_note", sa.Text(), nullable=True),
        sa.Column("attribution", sa.String(length=120), nullable=False),
        sa.Column("terms_checked_at", sa.Date(), nullable=True),
        sa.Column("last_loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_data_sources")),
        schema="market",
    )
    op.create_table(
        "etl_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job", sa.String(length=60), nullable=False),
        sa.Column("period", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed', 'skipped')",
            name=op.f("ck_etl_runs_status_valido"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etl_runs")),
        schema="market",
    )
    op.create_index(
        "ix_etl_runs_job_period", "etl_runs", ["job", "period"], unique=False, schema="market"
    )
    op.create_index(
        "ix_etl_runs_job_started", "etl_runs", ["job", "started_at"], unique=False, schema="market"
    )
    op.create_table(
        "financial_statements",
        sa.Column("cvm_code", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("statement", sa.String(length=12), nullable=False),
        sa.Column("consolidated", sa.Boolean(), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("account_name", sa.String(length=300), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_type IN ('annual', 'quarterly')",
            name=op.f("ck_financial_statements_period_type_valido"),
        ),
        sa.CheckConstraint(
            "statement IN ('dre', 'bp_ativo', 'bp_passivo', 'dfc', 'dra', 'dmpl')",
            name=op.f("ck_financial_statements_statement_valido"),
        ),
        sa.PrimaryKeyConstraint(
            "cvm_code",
            "period_end",
            "period_type",
            "statement",
            "consolidated",
            "account_code",
            name=op.f("pk_financial_statements"),
        ),
        schema="market",
    )
    op.create_index(
        "ix_financial_statements_lookup",
        "financial_statements",
        ["cvm_code", "statement", "period_end"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "indices",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("b3_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rebalance_note", sa.String(length=200), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_indices")),
        schema="market",
    )
    op.create_table(
        "macro_series",
        sa.Column("series", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "series IN ('selic', 'selic_meta', 'cdi', 'ipca', 'igpm', 'ptax_venda', 'ptax_compra')",
            name=op.f("ck_macro_series_series_valida"),
        ),
        sa.PrimaryKeyConstraint("series", "date", name=op.f("pk_macro_series")),
        schema="market",
    )
    op.create_index("ix_macro_series_date", "macro_series", ["date"], unique=False, schema="market")
    op.create_table(
        "sectors",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("subsector", sa.String(length=120), nullable=True),
        sa.Column("securities_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_sectors")),
        schema="market",
    )
    op.create_table(
        "securities",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("cvm_code", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=2), server_default="br", nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("trade_name", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("subsector", sa.String(length=120), nullable=True),
        sa.Column("segment", sa.String(length=120), nullable=True),
        sa.Column("sector_slug", sa.String(length=80), nullable=True),
        sa.Column("listing_segment", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("ri_url", sa.Text(), nullable=True),
        sa.Column("etf_index_slug", sa.String(length=80), nullable=True),
        sa.Column("bdr_ratio", sa.String(length=20), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("market IN ('br', 'us')", name=op.f("ck_securities_market_valido")),
        sa.CheckConstraint(
            "type IN ('stock', 'unit', 'bdr', 'etf', 'fii', 'fiagro', 'other')",
            name=op.f("ck_securities_type_valido"),
        ),
        sa.PrimaryKeyConstraint("ticker", name=op.f("pk_securities")),
        schema="market",
    )
    op.create_index(
        "ix_securities_company_name_trgm",
        "securities",
        [sa.literal_column("market.immutable_unaccent(lower(company_name)) public.gin_trgm_ops")],
        unique=False,
        schema="market",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_securities_cvm_code", "securities", ["cvm_code"], unique=False, schema="market"
    )
    op.create_index(
        "ix_securities_sector_slug", "securities", ["sector_slug"], unique=False, schema="market"
    )
    op.create_index(
        "ix_securities_type_status", "securities", ["type", "status"], unique=False, schema="market"
    )
    op.create_table(
        "treasury_bonds",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("index_type", sa.String(length=20), nullable=False),
        sa.Column("maturity", sa.Date(), nullable=False),
        sa.Column("coupon", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_treasury_bonds")),
        schema="market",
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("value_per_share", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("ratio", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('dividend', 'jcp', 'fii_income', 'split', 'reverse_split', 'bonus', 'subscription')",
            name=op.f("ck_corporate_actions_kind_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["market.securities.ticker"],
            name=op.f("fk_corporate_actions_ticker_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        schema="market",
    )
    op.create_index(
        "ix_corporate_actions_payment_date",
        "corporate_actions",
        ["payment_date"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "ix_corporate_actions_ticker_ex_date",
        "corporate_actions",
        ["ticker", "ex_date"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "uq_corporate_actions_evento",
        "corporate_actions",
        ["ticker", "kind", "ex_date", "value_per_share"],
        unique=True,
        schema="market",
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "crypto_daily",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price_brl", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("market_cap_brl", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("volume_brl", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["market.crypto_assets.id"],
            name=op.f("fk_crypto_daily_id_crypto_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "date", name=op.f("pk_crypto_daily")),
        schema="market",
    )
    op.create_index("ix_crypto_daily_date", "crypto_daily", ["date"], unique=False, schema="market")
    op.create_table(
        "crypto_metrics",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_brl", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("change_24h", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("change_7d", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("market_cap_brl", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("volume_24h_brl", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("circulating_supply", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("max_supply", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("ath_brl", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("ath_date", sa.Date(), nullable=True),
        sa.Column("btc_dominance", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["market.crypto_assets.id"],
            name=op.f("fk_crypto_metrics_id_crypto_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "captured_at", name=op.f("pk_crypto_metrics")),
        schema="market",
    )
    op.create_index(
        "ix_crypto_metrics_captured_at",
        "crypto_metrics",
        ["captured_at"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "fii_reports",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("nav", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("nav_per_share", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("shares", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("shareholders", sa.Integer(), nullable=True),
        sa.Column("income_per_share", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("vacancy_physical", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("vacancy_financial", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("admin_fee", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("manager", sa.String(length=200), nullable=True),
        sa.Column("administrator", sa.String(length=200), nullable=True),
        sa.Column("segment", sa.String(length=60), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["market.securities.ticker"],
            name=op.f("fk_fii_reports_ticker_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ticker", "period", name=op.f("pk_fii_reports")),
        schema="market",
    )
    op.create_index(
        "ix_fii_reports_period", "fii_reports", ["period"], unique=False, schema="market"
    )
    op.create_table(
        "index_compositions",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("theoretical_qty", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["market.indices.slug"],
            name=op.f("fk_index_compositions_slug_indices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("slug", "date", "ticker", name=op.f("pk_index_compositions")),
        schema="market",
    )
    op.create_index(
        "ix_index_compositions_ticker",
        "index_compositions",
        ["ticker"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "index_daily",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("change_pct", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["market.indices.slug"],
            name=op.f("fk_index_daily_slug_indices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("slug", "date", name=op.f("pk_index_daily")),
        schema="market",
    )
    op.create_index("ix_index_daily_date", "index_daily", ["date"], unique=False, schema="market")
    op.create_table(
        "indicators_daily",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("pe", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("pb", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("ev_ebitda", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("ev_ebit", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("psr", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("dy_12m", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("payout", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("roe", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("roic", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("roa", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("ebitda_margin", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("net_margin", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("net_debt_ebitda", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("net_debt_equity", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("current_ratio", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("revenue_cagr_5y", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("earnings_cagr_5y", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("eps", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("bvps", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("pvp", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("missing_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["market.securities.ticker"],
            name=op.f("fk_indicators_daily_ticker_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ticker", "date", name=op.f("pk_indicators_daily")),
        schema="market",
    )
    op.create_index(
        "ix_indicators_daily_date", "indicators_daily", ["date"], unique=False, schema="market"
    )
    op.create_table(
        "treasury_daily",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("buy_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("sell_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("buy_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("sell_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["market.treasury_bonds.slug"],
            name=op.f("fk_treasury_daily_slug_treasury_bonds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("slug", "date", name=op.f("pk_treasury_daily")),
        schema="market",
    )
    op.create_index(
        "ix_treasury_daily_date", "treasury_daily", ["date"], unique=False, schema="market"
    )
    # ### end Alembic commands ###

    # Partições de daily_quotes: do primeiro ano do COTAHIST até o ano que vem (o job
    # `cotahist_daily` cria a do ano novo, mas a virada não pode depender disso).
    connection = op.get_bind()
    create_year_partitions(connection, range(FIRST_YEAR, date.today().year + 2))

    # Estado das fontes. ON CONFLICT: reaplicar a migration não sobrescreve uma
    # verificação mais recente feita à mão.
    op.bulk_insert(
        sa.table(
            "data_sources",
            sa.column("source", sa.String),
            sa.column("url", sa.Text),
            sa.column("attribution", sa.String),
            sa.column("license_note", sa.Text),
            sa.column("terms_checked_at", sa.Date),
            schema="market",
        ),
        list(DATA_SOURCES),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_treasury_daily_date", table_name="treasury_daily", schema="market")
    op.drop_table("treasury_daily", schema="market")
    op.drop_index("ix_indicators_daily_date", table_name="indicators_daily", schema="market")
    op.drop_table("indicators_daily", schema="market")
    op.drop_index("ix_index_daily_date", table_name="index_daily", schema="market")
    op.drop_table("index_daily", schema="market")
    op.drop_index("ix_index_compositions_ticker", table_name="index_compositions", schema="market")
    op.drop_table("index_compositions", schema="market")
    op.drop_index("ix_fii_reports_period", table_name="fii_reports", schema="market")
    op.drop_table("fii_reports", schema="market")
    op.drop_index("ix_crypto_metrics_captured_at", table_name="crypto_metrics", schema="market")
    op.drop_table("crypto_metrics", schema="market")
    op.drop_index("ix_crypto_daily_date", table_name="crypto_daily", schema="market")
    op.drop_table("crypto_daily", schema="market")
    op.drop_index(
        "uq_corporate_actions_evento",
        table_name="corporate_actions",
        schema="market",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(
        "ix_corporate_actions_ticker_ex_date", table_name="corporate_actions", schema="market"
    )
    op.drop_index(
        "ix_corporate_actions_payment_date", table_name="corporate_actions", schema="market"
    )
    op.drop_table("corporate_actions", schema="market")
    op.drop_table("treasury_bonds", schema="market")
    op.drop_index("ix_securities_type_status", table_name="securities", schema="market")
    op.drop_index("ix_securities_sector_slug", table_name="securities", schema="market")
    op.drop_index("ix_securities_cvm_code", table_name="securities", schema="market")
    op.drop_index(
        "ix_securities_company_name_trgm",
        table_name="securities",
        schema="market",
        postgresql_using="gin",
    )
    op.drop_table("securities", schema="market")
    op.drop_table("sectors", schema="market")
    op.drop_index("ix_macro_series_date", table_name="macro_series", schema="market")
    op.drop_table("macro_series", schema="market")
    op.drop_table("indices", schema="market")
    op.drop_index(
        "ix_financial_statements_lookup", table_name="financial_statements", schema="market"
    )
    op.drop_table("financial_statements", schema="market")
    op.drop_index("ix_etl_runs_job_started", table_name="etl_runs", schema="market")
    op.drop_index("ix_etl_runs_job_period", table_name="etl_runs", schema="market")
    op.drop_table("etl_runs", schema="market")
    op.drop_table("data_sources", schema="market")
    op.drop_index("ix_daily_quotes_date", table_name="daily_quotes", schema="market")
    op.drop_table("daily_quotes", schema="market")
    op.drop_table("crypto_assets", schema="market")
    op.drop_table("company_facts", schema="market")
    op.drop_index(
        "ix_company_documents_ticker_delivered", table_name="company_documents", schema="market"
    )
    op.drop_index(
        "ix_company_documents_delivered_at", table_name="company_documents", schema="market"
    )
    op.drop_index(
        "ix_company_documents_cvm_code_delivered", table_name="company_documents", schema="market"
    )
    op.drop_table("company_documents", schema="market")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS market.immutable_unaccent(text)")
